# Changes here will be overwritten by Copier
_commit: v0.9.2
_src_path: https://gitee.com/gooker_young/coopie.git
author_email: gooker_young@qq.com
author_name: gookeryoung
coverage_fail_under: 95
description: 通用科学计算仿真分析平台。
license: MIT
max_python_version: '3.14'
min_python_version: '3.11'
package_name: zylab
project_name: zylab
project_type: gui
use_cicd: true
use_docker: true
use_docs: true
use_domestic_mirrors: true
use_tox: true

