"""Qt 兼容层：PySide2（Python<=3.10 / Win7）与 PySide6（>=3.11）统一导入.

GUI 模块一律从这里导入 Qt 符号，版本差异（exec_/exec、枚举路径）在此收拢。
"""

from __future__ import annotations

try:
    from PySide6.QtCore import (
        QAbstractTableModel,
        QByteArray,
        QEvent,
        QModelIndex,
        QObject,
        QPoint,
        QPointF,
        QRectF,
        QSize,
        Qt,
        QTimer,
        Signal,
        Slot,
    )
    from PySide6.QtGui import (
        QBrush,
        QColor,
        QContextMenuEvent,
        QFont,
        QIcon,
        QKeyEvent,
        QMouseEvent,
        QPainter,
        QPainterPath,
        QPen,
        QPixmap,
        QTextCursor,
    )
    from PySide6.QtWidgets import (
        QAbstractItemView,
        QApplication,
        QComboBox,
        QDoubleSpinBox,
        QFileDialog,
        QFormLayout,
        QFrame,
        QGraphicsItem,
        QGraphicsPathItem,
        QGraphicsScene,
        QGraphicsView,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMenu,
        QPlainTextEdit,
        QProgressBar,
        QPushButton,
        QScrollArea,
        QSpinBox,
        QSplitter,
        QStackedWidget,
        QTableView,
        QTableWidget,
        QTableWidgetItem,
        QTabWidget,
        QVBoxLayout,
        QWidget,
    )

    QT_API = "pyside6"
except ImportError:  # pragma: no cover（3.8 环境走此分支）
    from PySide2.QtCore import (  # type: ignore[missing-import]
        QAbstractTableModel,
        QByteArray,
        QEvent,
        QModelIndex,
        QObject,
        QPoint,
        QPointF,
        QRectF,
        QSize,
        Qt,
        QTimer,
        Signal,
        Slot,
    )
    from PySide2.QtGui import (  # type: ignore[missing-import]
        QBrush,
        QColor,
        QContextMenuEvent,
        QFont,
        QIcon,
        QKeyEvent,
        QMouseEvent,
        QPainter,
        QPainterPath,
        QPen,
        QPixmap,
        QTextCursor,
    )
    from PySide2.QtWidgets import (  # type: ignore[missing-import]
        QAbstractItemView,
        QApplication,
        QComboBox,
        QDoubleSpinBox,
        QFileDialog,
        QFormLayout,
        QFrame,
        QGraphicsItem,
        QGraphicsPathItem,
        QGraphicsScene,
        QGraphicsView,
        QGroupBox,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMenu,
        QPlainTextEdit,
        QProgressBar,
        QPushButton,
        QScrollArea,
        QSpinBox,
        QSplitter,
        QStackedWidget,
        QTableView,
        QTableWidget,
        QTableWidgetItem,
        QTabWidget,
        QVBoxLayout,
        QWidget,
    )

    QT_API = "pyside2"

__all__ = [
    "QT_API",
    "QAbstractItemView",
    "QAbstractTableModel",
    "QApplication",
    "QBrush",
    "QByteArray",
    "QColor",
    "QComboBox",
    "QContextMenuEvent",
    "QDoubleSpinBox",
    "QEvent",
    "QFileDialog",
    "QFont",
    "QFormLayout",
    "QFrame",
    "QGraphicsItem",
    "QGraphicsPathItem",
    "QGraphicsScene",
    "QGraphicsView",
    "QGroupBox",
    "QHBoxLayout",
    "QHeaderView",
    "QIcon",
    "QInputDialog",
    "QKeyEvent",
    "QLabel",
    "QLineEdit",
    "QListWidget",
    "QListWidgetItem",
    "QMainWindow",
    "QMenu",
    "QModelIndex",
    "QMouseEvent",
    "QObject",
    "QPainter",
    "QPainterPath",
    "QPen",
    "QPixmap",
    "QPlainTextEdit",
    "QPoint",
    "QPointF",
    "QProgressBar",
    "QPushButton",
    "QRectF",
    "QScrollArea",
    "QSize",
    "QSpinBox",
    "QSplitter",
    "QStackedWidget",
    "QTabWidget",
    "QTableView",
    "QTableWidget",
    "QTableWidgetItem",
    "QTextCursor",
    "QTimer",
    "QVBoxLayout",
    "QWidget",
    "Qt",
    "Signal",
    "Slot",
    "exec_app",
    "mouse_event_pos",
]


def exec_app(app: QApplication) -> int:
    """启动事件循环（兼容 PySide2 的 exec_ 与 PySide6 的 exec）."""
    run = app.exec if hasattr(app, "exec") else app.exec_  # type: ignore[union-attr]
    return int(run())


def mouse_event_pos(event: QMouseEvent) -> QPoint:
    """鼠标事件视图坐标（Qt6 的 position / Qt5 的 pos 兼容）."""
    pos = event.position() if hasattr(event, "position") else event.pos()  # type: ignore[union-attr]
    # PySide2 的 pos() 已是 QPoint（无 toPoint），Qt6 的 position() 是 QPointF 须转换
    return pos.toPoint() if hasattr(pos, "toPoint") else pos  # type: ignore[union-attr]
