"""设计令牌：色彩/排版/间距/尺寸，QSS 与代码统一引用此处常量（禁止散落硬编码）."""

from __future__ import annotations

__all__ = [
    "COLOR_ACCENT",
    "COLOR_BG_APP",
    "COLOR_BG_MUTED",
    "COLOR_BORDER",
    "COLOR_DANGER",
    "COLOR_ERROR_TEXT",
    "COLOR_PRIMARY",
    "COLOR_PRIMARY_DARK",
    "COLOR_SUCCESS",
    "COLOR_TEXT_ON_PRIMARY",
    "COLOR_TEXT_PRIMARY",
    "COLOR_TEXT_SECONDARY",
    "COLOR_WARNING",
    "CONTROL_HEIGHT",
    "CONTROL_HEIGHT_SM",
    "FONT_BODY",
    "FONT_CAPTION",
    "FONT_FAMILY",
    "FONT_HEADING",
    "FONT_MONO",
    "FONT_TITLE",
    "HEADER_HEIGHT",
    "QSS_TOKENS",
    "RADIUS_MD",
    "RADIUS_SM",
    "SIDEBAR_WIDTH",
    "SPACING_LG",
    "SPACING_MD",
    "SPACING_SM",
    "SPACING_XL",
    "SPACING_XS",
    "STATUSBAR_HEIGHT",
]

# 色彩
COLOR_PRIMARY = "#0887A0"
COLOR_PRIMARY_DARK = "#00829E"
COLOR_ACCENT = "#87C6BB"
COLOR_TEXT_ON_PRIMARY = "#FFFFFF"
COLOR_TEXT_PRIMARY = "#2C3E50"
COLOR_TEXT_SECONDARY = "#518394"
COLOR_BG_APP = "#FFFFFF"
COLOR_BG_MUTED = "#E5EDE0"
COLOR_BORDER = "#D1DDE2"
COLOR_DANGER = "#E74C3C"
COLOR_WARNING = "#F39C12"
COLOR_SUCCESS = "#27AE60"
COLOR_ERROR_TEXT = "#C0392B"  # REPL 错误/stderr 文本

# 排版
FONT_FAMILY = '"PingFang SC", "Microsoft YaHei", "Segoe UI", "Helvetica Neue", Arial, sans-serif'
FONT_MONO = '"Consolas", "Cascadia Mono", "JetBrains Mono", monospace'
FONT_TITLE = "18px"
FONT_HEADING = "15px"
FONT_BODY = "13px"
FONT_CAPTION = "11px"

# 间距（8px 基准网格）
SPACING_XS = 4
SPACING_SM = 8
SPACING_MD = 16
SPACING_LG = 24
SPACING_XL = 32

# 圆角与尺寸
RADIUS_SM = "4px"
RADIUS_MD = "6px"
CONTROL_HEIGHT = "32px"
CONTROL_HEIGHT_SM = "26px"
SIDEBAR_WIDTH = 200
HEADER_HEIGHT = 40
STATUSBAR_HEIGHT = 28

# QSS 占位符映射（string.Template.substitute 入参）
QSS_TOKENS = {
    "COLOR_PRIMARY": COLOR_PRIMARY,
    "COLOR_PRIMARY_DARK": COLOR_PRIMARY_DARK,
    "COLOR_ACCENT": COLOR_ACCENT,
    "COLOR_TEXT_ON_PRIMARY": COLOR_TEXT_ON_PRIMARY,
    "COLOR_TEXT_PRIMARY": COLOR_TEXT_PRIMARY,
    "COLOR_TEXT_SECONDARY": COLOR_TEXT_SECONDARY,
    "COLOR_BG_APP": COLOR_BG_APP,
    "COLOR_BG_MUTED": COLOR_BG_MUTED,
    "COLOR_BORDER": COLOR_BORDER,
    "COLOR_DANGER": COLOR_DANGER,
    "COLOR_WARNING": COLOR_WARNING,
    "COLOR_SUCCESS": COLOR_SUCCESS,
    "COLOR_ERROR_TEXT": COLOR_ERROR_TEXT,
    "FONT_FAMILY": FONT_FAMILY,
    "FONT_MONO": FONT_MONO,
    "FONT_TITLE": FONT_TITLE,
    "FONT_HEADING": FONT_HEADING,
    "FONT_BODY": FONT_BODY,
    "FONT_CAPTION": FONT_CAPTION,
    "RADIUS_SM": RADIUS_SM,
    "RADIUS_MD": RADIUS_MD,
    "CONTROL_HEIGHT": CONTROL_HEIGHT,
    "CONTROL_HEIGHT_SM": CONTROL_HEIGHT_SM,
}
